from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.source import Source
from app.domain.vehicle import Vehicle


class IVehicleRepository(Protocol):
    async def add(self, vehicle: Vehicle) -> Vehicle: ...
    async def get(self, id: UUID) -> Vehicle | None: ...
    async def get_with_sources(self, id: UUID) -> Vehicle | None: ...
    async def list(self) -> list[Vehicle]: ...
    async def update(self, vehicle: Vehicle) -> Vehicle: ...
    async def delete(self, id: UUID) -> None: ...


class ISourceRepository(Protocol):
    async def add(self, source: Source) -> Source: ...
    async def get(self, id: UUID) -> Source | None: ...
    async def list(self) -> list[Source]: ...
    async def update(self, source: Source) -> Source: ...
    async def delete(self, id: UUID) -> None: ...
    async def link_vehicle(self, source_id: UUID, vehicle_id: UUID) -> None: ...
    async def unlink_vehicle(self, source_id: UUID, vehicle_id: UUID) -> None: ...
    async def get_vehicles_for_source(self, source_id: UUID) -> list[Vehicle]: ...
