helm:
  parameters:
  - name: images.backend.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-backend/api
    forcestring: true
  - name: images.backend.tag
    value: latest@sha256:c97ff57fbb1e7b90d0445ff9b70fd06e1ca86e325dee59a877b22646b253d53a
    forcestring: true
  - name: images.frontend.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-frontend/deer-flow-frontend
    forcestring: true
  - name: images.frontend.tag
    value: latest@sha256:c3489af5ff6d34c17ebf980238ea1784dba5e5a7f5a83847b3a8bed969112629
    forcestring: true
  - name: images.provisioner.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-provisioner/provisioner
    forcestring: true
  - name: images.provisioner.tag
    value: latest@sha256:7e822a67d37d50d7a8f28892ca8f75696d064c34c9891fe935bcaabb3899b6c4
    forcestring: true
