helm:
  parameters:
  - name: images.backend.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-backend/api
    forcestring: true
  - name: images.backend.tag
    value: latest@sha256:b86ba80ba408b6bf735875ab53789c317f61415f67a380aa7bea919946b612d8
    forcestring: true
  - name: images.frontend.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-frontend/deer-flow-frontend
    forcestring: true
  - name: images.frontend.tag
    value: latest@sha256:4a758dd6ac2d717584f0fc51904115f3c8eb7bb1b4bdae1a0b188e210219857e
    forcestring: true
  - name: images.provisioner.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/deer-flow-provisioner/provisioner
    forcestring: true
  - name: images.provisioner.tag
    value: latest@sha256:a4f341eaa7609642bbda144a77c6ff4e8ad0aed6209008591e7b73b98b052522
    forcestring: true
